---
- name: Install packages
  ansible.builtin.homebrew:
    name:   "{{ item.package_name }}"
    state:  present
  with_items:
    - package_name: git
    - package_name: gpg
    - package_name: pinentry-mac

- name: Configure signing key
  ansible.builtin.git_config:
    name:   user.signingKey
    scope:  global
    value:  "{{ git_gpg.git.signing_key }}"

- name: Sign commits automatically
  ansible.builtin.git_config:
    name:   commit.gpgsign
    scope:  global
    value:  "{{ git_gpg.git.auto_sign }}"

- name: Configure gpg-agent
  ansible.builtin.blockinfile:
    block: |
      use-standard-socket
      pinentry-program /usr/local/bin/pinentry-mac
    create: true
    dest:   ~/.gnupg/gpg-agent.conf
    mode:   u+rw,g-r,o-r
  notify:
    - Stop gpg-agent
